### ISSUE TITLE
Proposal to adopt and refresh this repository for "RSE Good Practices"

### ISSUE THREAD

**Issue by HChughtai** [UCL-ARC/coding-standards#19]
## Summary

As part of ongoing initiatives to strengthen the RSE team and our practices, we've (re)identified that it's important to have a default place to write down our thoughts, experience and ideas about what good practice looks like for RSEs in the many parts of Collaborations projects lifecycle (i.e. planning, initiation, construction, testing, etc). By writing these down, we have a place to refer ourselves and collaborators to, as well as a place to invite feedback and change to processes.

"Coding standards" form part of these good practices, so rather than creating yet another location, we propose that we adopt and expand this repository to cover other aspects of RSE good practices forming a community driven "RSE Good Practices Handbook".

## Questions

> Some questions that may come up, and our initial thoughts (to be updated as we go along)

Is this a good idea? What are the downsides?
  - ???

Why not include this in existing internal docs? What is the argument for it to be public?
  - Open by default, allows collaborators to see how we work, expands our Ways of Working doc

My subgroup/programming-language of choice/xyz already has a good place for this? Should I move it
  - Link it from here 

Why only RSEs? Is this only for Collaborations? What about profession xyz that has similar needs?
  - ???

## Next Steps
- I will circulate this on Slack (a heads up for those who see this issue before I do)
- Feedback in the comments below on this issue please.

**Comment by milanmlft** [comment]
I like this idea! I think we were already drifting beyond just coding standards with the suggestion to add git/github recommendations (#7). It makes sense to me to bundle these recommendations in one place.

> Why only RSEs? Is this only for Collaborations? What about profession xyz that has similar needs?
I think it makes sense to focus on RSEs, as I imagine it will be mostly us that will be generating these recommendations, and also to not make it too generic, but that doesn't mean that others can't benefit from it of course (since we make it public)!

**Comment by gsvarovsky** [comment]
Need to establish relationship with https://github.com/UCL-ARC/research-software-documentation/blob/main/processes/programming_projects/group_practices.md

**Comment by samcunliffe** [comment]
> Need to establish relationship with https://github.com/UCL-ARC/research-software-documentation/blob/main/processes/programming_projects/group_practices.md

The idea was originally to migrate the coding standards (and good practices, if you like) _out_ from our private docs into a public place. Hopefully there are no(?) coding standards in research-software-documentation 🥺 

The stretch-goal here is to merge this back into https://github.com/UCL-ARC/arc-internal-documentation (eventually) and make portions of that public. So there will be one source of truth.

**Comment by samcunliffe** [comment]
I think the proposal is a good one, but I would be cautious about the title. (Why DRAFT?)

**Comment by HChughtai** [comment]
Discussion between @milanmlft, @samcunliffe, @pineapple-cat, @K-Meech and @HChughtai at a docathon. Decision made to proceed and discussion about naming and scope started

- Suggestion to call the repository: `Research Software Good Practices and Coding Standards` #22
- Suggestion to rename the repository to `good` (blame @milanmlft) #23
