### ISSUE TITLE
Decide on repository structure

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/coding-standards#2]
We need to decide on how to structure the repository.

As an initial suggestion possibly something like 

```
├── README.md
├── cpp
│   └── README.md
├── fortran
│   └── README.md
├── java
│   └── README.md
├── julia
│   └── README.md
├── matlab
│   └── README.md
├── python
│   └── README.md
└── r
    └── README.md
```

with per-language README.md giving human readable descriptions of recommended standards and/or linking to the external standards we recommend? We can then also possibly add a per language linter configuration to each directory where relevant.

With this sort of structure we could then have site both directly viewable on GitHub and use Jekyll GitHub pages integration to also allow viewing at https://github-pages.arc.ucl.ac.uk/coding-standards/ possibly using something like https://github.com/benbalter/jekyll-readme-index to simplify URLs

Edit: Updated `c++` to `cpp` to avoid having to encode `+` in URLs

**Comment by matt-graham** [comment]
> possibly using something like https://github.com/benbalter/jekyll-readme-index to simplify URLs

Interestingly https://github-pages.arc.ucl.ac.uk/coding-standards/  already shows the rendered version of the current root `README.md` file so possibly there is now built in support for this, though we need to check if this would also work for subdirectories so that https://github-pages.arc.ucl.ac.uk/coding-standards/fortran would show `fortran/README.md` for example.

We may also want to consider `cpp` rather than `c++` to avoid having to encode as `c%2B%2B`

**Comment by matt-graham** [comment]
Created a branch following suggested structure above and temporarily set it to be GitHub Pages source for testing. It looks like `README.md` files in subdirectories do automatically get used as index pages, for example https://github-pages.arc.ucl.ac.uk/coding-standards/python/

**Comment by paddyroddy** [comment]
Are we also including other files here or just docs stuff?

**Comment by matt-graham** [comment]
Seems like most people are okay with structure suggested above or at least not strongly against so I'll open a PR from the `mmg/initial-structure` branch as @milanmlft's R PR (#8) is currently targetting that branch.
