### ISSUE TITLE
Recommendations for C++ standards

### ISSUE THREAD

**Issue by samcunliffe** [UCL-ARC/coding-standards#6]
There are a few possibilities that I know of:

* [Google style C++](https://google.github.io/styleguide/cppguide.html) used by TDMS.
* [ISO C++ Core](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines)
* [Linux Kernel style guides](https://www.kernel.org/doc/html/v4.10/process/coding-style.html)

Left up to me, I'd probably vote Google style.

## Tools / linters

* [clang-format](https://clang.llvm.org/docs/ClangFormat.html) for all your linting needs.
   - Plays well with [pre-commit](https://github.com/UCL/TDMS/pull/222). 
   - Has a VSCode extension.

**Comment by samcunliffe** [comment]
@krishnakumarg1984 can you edit either the issue description or add a comment listing out the linters that you're proposing.

And I don't think Google style is really "at loggerheads". Preprocessor directives mean _their_ braces (when needed) must go on their own line. But in all other cases, they don't.

Ditto if you have a preferred standard please add to the list.

Tagging @mmcleod89 for extra C++ wisdom.

**Comment by krishnakumarg1984** [comment]
### LSPs
- [Clangd](https://clangd.llvm.org/). I use this.
- [CCLS](https://github.com/MaskRay/ccls). Didn't have good luck with this.

### These are some of the static checkers I use
- [clang-tidy](https://clang.llvm.org/extra/clang-tidy/)
- [cpplint](https://github.com/cpplint/cpplint)
- [cppcheck](https://cppcheck.sourceforge.io/)

### Formatter
- [clang-format](https://pypi.org/project/clang-format/)

### What I'd like to use in the future:
- [gccdiag](https://gitlab.com/andrejr/gccdiag)
- [Infer](https://fbinfer.com/). Could never make it work.
- [NASA's Ikos](https://github.com/NASA-SW-VnV/ikos). Cool sounding tagline:  Static analyzer for C/C++ based on the _theory of Abstract Interpretation_ (whatever that means NASA scientists should hopefully be able to tell us mortals). I never managed to compile this :)   

### Commercial static-checker:
- [PVS-Studio](https://pvs-studio.com/en/pvs-studio/). This is an outstanding one, and free to use for FLOSS projects

### Debugger
- [CodeLLDB](https://github.com/vadimcn/codelldb). Supports the DAP protocol for editor/IDE-agnostic debugging.

### Others
- [Clazy](https://github.com/KDE/clazy). a static checker for QT projects (such as K-plan)

**Comment by krishnakumarg1984** [comment]
@samcunliffe 

>And I don't think Google style is really "at loggerheads". Preprocessor directives mean their braces (when needed) must go on their own line. But in all other cases, they don't.

Ah. Let me clarify. What I meant was the following: 
_I prefer the trailing opening braces (i.e. Google's style) myself. However, clang-format until (v13 or so) didn't understand openmp semantics and annoyingly auto-formatted upon every save to incorrectly place the opening brace at the end of a preceding openmp pre-processor directive line. It would be helpful for us to verify if the most recent clang-format (17.x as of today) understands and formats the code correctly._

**Comment by ivanperez-keera** [comment]
@krishnakumarg1984 I'm the current maintainer of IKOS.

There's been a new release and we've now switched to a quarterly release cycle.

Compilation should be straightforward, but please open an issue of something doesn't work. I know that packages for [nix](https://search.nixos.org/packages?channel=23.11&show=ikos&from=0&size=50&sort=relevance&type=packages&query=ikos) and [FreeBSD](https://www.freshports.org/devel/ikos/) exist . We'll be trying to provide Debian/Ubuntu packages next.
